# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main2.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(782, 221)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setWindowIcon(QtGui.QIcon('logo.png'))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 781, 204))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_name = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_name.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name.sizePolicy().hasHeightForWidth())
        self.label_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_name)
        self.text_name = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_name.sizePolicy().hasHeightForWidth())
        self.text_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.text_name.setFont(font)
        self.text_name.setObjectName("text_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.text_name)
        self.label_tile_path = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_tile_path.setFont(font)
        self.label_tile_path.setObjectName("label_tile_path")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_tile_path)
        self.HLayout_Tile = QtWidgets.QHBoxLayout()
        self.HLayout_Tile.setObjectName("HLayout_Tile")
        self.text_path = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.text_path.setFont(font)
        self.text_path.setObjectName("text_path")
        self.HLayout_Tile.addWidget(self.text_path)
        self.button_search_tile = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.button_search_tile.setFont(font)
        self.button_search_tile.setObjectName("button_search_tile")
        self.HLayout_Tile.addWidget(self.button_search_tile)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.HLayout_Tile)
        self.radio_dark = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radio_dark.setText("")
        self.radio_dark.setObjectName("radio_dark")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.radio_dark)
        self.label_radio_dark = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_radio_dark.setFont(font)
        self.label_radio_dark.setObjectName("label_radio_dark")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_radio_dark)
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_2.setText("")
        self.radioButton_2.setObjectName("radioButton_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.radioButton_2)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_3.setText("")
        self.radioButton_3.setObjectName("radioButton_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.radioButton_3)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.button_submit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.button_submit.setFont(font)
        self.button_submit.setObjectName("button_submit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.button_submit)
        self.text_url = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.text_url.setFont(font)
        self.text_url.setObjectName("text_url")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.text_url)
        self.label_url = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_url.setFont(font)
        self.label_url.setObjectName("label_url")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_url)
        self.horizontalLayout.addLayout(self.formLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TileFactory"))
        self.label_name.setToolTip(_translate("MainWindow", "The name of the tile"))
        self.label_name.setText(_translate("MainWindow", "Name"))
        self.label_tile_path.setText(_translate("MainWindow", "Tile"))
        self.button_search_tile.setText(_translate("MainWindow", "Find"))
        self.label_radio_dark.setText(_translate("MainWindow", "Dark text on tile"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.button_submit.setText(_translate("MainWindow", "Generate!"))
        self.label_url.setText(_translate("MainWindow", "URL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

